// <auto-generated />
using System;
using CafeLokaal.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeLokaal.Api.Migrations
{
    [DbContext(typeof(CafeLokaalDBContext))]
    [Migration("20250730185050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CafeLokaal.Api.Models.CafeOrderModel", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OrderStep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ProcessDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProcessTime")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("CafeOrderModels");
                });
#pragma warning restore 612, 618
        }
    }
}
