name: Deploy CafeLokaal Full Stack

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 'latest'
  NODE_VERSION: 'latest'

jobs:
  build-and-deploy-api:
    name: Build and Deploy .NET API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: latest

      - name: Restore dependencies
        working-directory: ./CafeLokaal.Api
        run: dotnet restore

      - name: Build API
        working-directory: ./CafeLokaal.Api
        run: dotnet build --configuration Release --no-restore

      - name: Publish API
        working-directory: ./CafeLokaal.Api
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: cafelokaal-api       # change this to your API App Service name
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: ./api/publish

  build-and-deploy-frontend:
    name: Build and Deploy Angular Frontend
    runs-on: ubuntu-latest
    needs: build-and-deploy-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Angular App
        working-directory: ./frontend
        run: npm run build -- --configuration production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend/dist"             # Adjust if your dist path differs
          output_location: ""                        # Leave empty if already in dist
