services:
    api:
      image: cafelokaal-api:latest
      container_name: cafelokaal-api
      ports:
        - "5107:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};
        - Some__ApiKey=${API_KEY}
      depends_on:
        - mysql # optional if DB is managed separately
    mysql:
      image: mysql:8
      container_name: mysql-cafelokaal
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      volumes:
        - mysql_data:/var/lib/mysql
volumes:
  mysql_data: